version: "3.8"

services:
  pretix:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8345:80"
    volumes:
      - ./var/pretix-data:/data
      - ./etc/pretix:/etc/pretix
      - ./var/run/redis:/var/run/redis
    environment:
      - DJANGO_SETTINGS_MODULE=production_settings
    depends_on:
      - postgres
      - redis
    command: all

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=pretix
      - POSTGRES_DB=pretix
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    driver: bridge
